# Generated by Django 5.2.7 on 2025-10-26 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovie',
            name='favorite_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.favorite'),
        ),
        migrations.AlterField(
            model_name='favoritemovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie'),
        ),
    ]
